### ISSUE TITLE
Create a new tag with good version xml2json

### ISSUE THREAD

**Issue by jluccisano** [abdmob/x2js#10]
Actually the version on tag of xml2json is 1.1.5 or Master contains 1.1.7. Is it possible to create a new tag or delete and recreate the tag ?

**Comment by mfb** [comment]
I ran into this issue as well. version 1.1.7 fixed some bugs so would be good to have it correctly tagged.

**Comment by abdmob** [comment]
Sorry guys, fixed. I'm from Mercurial world - so I need some time to adapt here ^^
