### ISSUE TITLE
Working with integers??

### ISSUE THREAD

**Issue by andystocks** [abdmob/x2js#24]
Is it possible to avoid getting "" in numeric values when converting XML to JSON

`<xml><a>String</a><b>3</b></xml>` 
yeilds `{"xml":{"a":"String","b":"3"}}`

instead of 
`{"xml":{"a":"String","b":3}}`

**Comment by czeckd** [comment]
This is what I've done. After the initial conversion from xml to json, I pass the json object to another function to convert the strings into numbers, etc. So something like:

```
function convertJson(jsn) {
    jsn.xml.b = parseInt(jsn.xml.b, 10);
    return jsn;
}
```

**Comment by andystocks** [comment]
works brillant! thanks a lot @czeckd !

**Comment by andystocks** [comment]
Also, you can try this commit by @synec
https://github.com/abdmob/x2js/pull/9/commits/4baaaf0faea65227bcb3ce3e21f4b4c3b5631167
