### ISSUE TITLE
 https://x2js.googlecode.com/hg/xml2json.js  is not working

### ISSUE THREAD

**Issue by yowitin** [abdmob/x2js#28]
Hello, we have develope an app that included a link to the js file at https://x2js.googlecode.com/hg/xml2json.js
But this morning we saw that this link is not working...we  has include the js inside the app to solve the problem and it runs.
The problem is that until iTunes validates the app update, our clients cannot use it.
Does anyone know where must I notify this issue to Googlecode to solve it? 
Thanks!!

**Comment by chepe263** [comment]
As far as I know, [google code service is closed](http://google-opensource.blogspot.com/2015/03/farewell-to-google-code.html). You could use this link instead https://cdnjs.cloudflare.com/ajax/libs/x2js/1.2.0/xml2json.min.js

**Comment by abdolence** [comment]
Yes, chepe263 is right. You should change it to cdnjs. Google had decided to close Google Code.
